### ISSUE TITLE
finish example solr_fields and config for solr suffixer

### ISSUE THREAD

**Issue by queryluke** [trln/argot-ruby#3]

**Comment by queryluke** [comment]
@adjam @corylown @penumart 

I'm rethinking the suffixer code. Currently, anything not in the field config file defaults to:
- Stored
- UNindexed
- multivalued

But instead, I feel the default should be:
- text type
- indexed
- multivalued

As I look at the old endeca properties there are far more indexed properties than unindexed. Thoughts?

**Comment by penumart** [comment]
What are the pros and cons of the two approaches?

Shashi

**Comment by queryluke** [comment]
First Way:
The config file would list ALL indexed fields at the expense of repetitive code:
```
title_main:
  type: t
title_alt:
 type: t
title_sort:
  type: str
  attr:
    - sort
```
We would know all 3 of those field are indexed.

The other way, the config file would be much shorter at the expense of obfuscating what is indexed
```
title_sort:
  type: str
  attr:
    - sort
notes_additional:
  type: no-index
publication_year:
  type: i
```
